#!/bin/bash
#
# update-trivy-checksums.sh
#
# Checksums are stored locally in this repository so that a compromised or
# tampered trivy release cannot go undetected - if an attacker modifies a
# release asset upstream, the hash will no longer match what was recorded here.
#
# Fetches all trivy GitHub releases, downloads the official SHA256 checksums
# published by trivy for each release, and writes them into trivy_checksums.txt
# at the root of this repository.
#
# If trivy_checksums.txt already exists, every previously recorded hash is
# compared against the freshly fetched upstream value. A changed hash for an
# existing release asset is a sign of tampering and causes the script to abort
# with an error without updating the file.
#
# Run this script whenever a new trivy release should be added to
# trivy_checksums.txt. Commit the resulting file alongside any trivy_version
# pin change.

set -Eeuo pipefail

CHECKSUMS_FILE="$(dirname "$0")/../trivy_checksums.txt"
REPO="aquasecurity/trivy"

echo "Fetching trivy releases from GitHub ..."
releases=$(curl -sfL \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/${REPO}/releases?per_page=100" \
  | jq -r '.[].tag_name')

if [[ -z "${releases}" ]]; then
  echo "Error: no releases found." >&2
  exit 1
fi

# Build new checksums file from scratch into a temp file
TEMP_FILE="$(mktemp)"
trap 'rm -f "${TEMP_FILE}"' EXIT

{
  echo "# trivy SHA256 checksums"
  echo "# Generated by scripts/update-trivy-checksums.sh"
  echo "# Do not edit manually."
  echo "# Format: <filename>: <sha256>"
  echo ""

  for release in ${releases}; do
    release_num="${release/#v/}"
    checksums_url="https://github.com/${REPO}/releases/download/${release}/trivy_${release_num}_checksums.txt"

    checksums=$(curl -sfL "${checksums_url}" 2>/dev/null) || {
      echo "  Skipping ${release}: checksums file not available." >&2
      continue
    }

    # Only include release archives for supported platforms, sorted by filename.
    # grep runs before the awk swap because the original format is "<hash>  <filename>"
    # so the filename is at the end of the line where grep -E can match it.
    entries=$(echo "${checksums}" \
      | grep -E '\.(tar\.gz|zip)$' \
      | sort -k2 \
      | awk '{print $2 ": " $1}' || true)

    [[ -z "${entries}" ]] && continue

    echo "## ${release}"
    echo "${entries}"
    echo ""
  done
} > "${TEMP_FILE}"

# Compare against existing file to detect tampered upstream checksums
if [[ -f "${CHECKSUMS_FILE}" ]]; then
  # Only compare data lines (skip comments and blank lines)
  existing_entries=$(grep -v '^#' "${CHECKSUMS_FILE}" | grep -v '^$' || true)

  tampered=0
  while IFS= read -r line; do
    [[ -z "${line}" ]] && continue
    filename="${line%%:*}"
    existing_hash="${line##*: }"
    # Use fixed-string matching to avoid regex interpretation of dots in filenames
    new_hash=$(grep -m1 -F "${filename}:" "${TEMP_FILE}" | awk '{print $2}' || true)

    if [[ -z "${new_hash}" ]]; then
      # Entry disappeared from upstream — warn but do not treat as tampering
      echo "WARNING: entry no longer found upstream: ${line}" >&2
    elif [[ "${existing_hash}" != "${new_hash}" ]]; then
      echo "" >&2
      echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" >&2
      echo "!! ERROR: CHECKSUM MISMATCH - possible tampering detected !!" >&2
      echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" >&2
      echo "!! File    : ${filename}" >&2
      echo "!! Expected: ${existing_hash}" >&2
      echo "!! Got     : ${new_hash}" >&2
      echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" >&2
      echo "" >&2
      tampered=1
    fi
  done <<< "${existing_entries}"

  if [[ "${tampered}" -eq 1 ]]; then
    echo "ERROR: One or more previously recorded checksums differ from upstream. Aborting." >&2
    exit 1
  fi
fi

cp "${TEMP_FILE}" "${CHECKSUMS_FILE}"
echo "Done. Checksums written to ${CHECKSUMS_FILE}"
